name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-review"]
assignees:
  - "@me"
body:
  - type: markdown
    attributes:
      value: |
        感谢您提出功能建议！请详细描述您希望添加的功能。

  - type: dropdown
    id: feature-type
    attributes:
      label: 功能类型
      description: 这个功能请求属于哪个类别？
      options:
        - 检测功能增强
        - 新的认证方式支持
        - 报告格式改进
        - 性能优化
        - 用户界面改进
        - 配置选项增加
        - 文档改进
        - 其他
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个功能的优先级如何？
      options:
        - 高 (重要且紧急)
        - 中 (重要但不紧急)
        - 低 (有用但不重要)
        - 非常低 (可有可无)
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 问题描述
      description: 您想解决什么问题？描述当前的痛点或限制
      placeholder: |
        例如:
        - 当前无法检测某种类型的登录接口
        - 报告格式不够直观
        - 某些场景下性能较慢
        - 缺少某种配置选项
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: 解决方案
      description: 详细描述您建议的功能或解决方案
      placeholder: |
        详细描述您希望如何实现这个功能...
        
        例如:
        - 添加对JWT token认证的支持
        - 支持自定义报告模板
        - 增加多线程优化选项
        - 添加JSON格式的配置文件支持
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您是否考虑过其他解决方案？
      placeholder: 描述您考虑过的其他方法或工具...

  - type: textarea
    id: use-case
    attributes:
      label: 使用场景
      description: 详细描述这个功能的使用场景和目标用户
      placeholder: |
        谁会使用这个功能？在什么情况下使用？
        
        例如:
        - 企业安全团队进行内网扫描
        - 渗透测试人员进行授权测试
        - 系统管理员进行安全审计
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: 实现思路
      description: 如果您有实现这个功能的想法，请分享
      placeholder: |
        可选：如果您有技术实现的想法，请分享...
        
        例如:
        - 需要添加哪些新的依赖
        - 代码结构如何调整
        - 配置文件格式建议

  - type: textarea
    id: examples
    attributes:
      label: 示例
      description: 提供具体的使用示例或配置示例
      placeholder: |
        例如期望的命令行用法:
        ```bash
        python weak_password_checker.py --auth-type jwt --token-file tokens.txt
        ```
        
        或者期望的配置文件格式:
        ```yaml
        authentication:
          type: jwt
          token_file: tokens.txt
        ```

  - type: checkboxes
    id: implementation-willingness
    attributes:
      label: 实现意愿
      description: 您是否愿意参与实现这个功能？
      options:
        - label: 我愿意提交Pull Request来实现这个功能
        - label: 我可以提供测试用例
        - label: 我可以协助编写文档
        - label: 我可以参与功能设计讨论

  - type: checkboxes
    id: terms
    attributes:
      label: 确认
      description: 请确认以下事项
      options:
        - label: 我已经搜索了现有的功能请求，确认这不是重复建议
          required: true
        - label: 这个功能符合项目的目标和范围
          required: true
        - label: 我已经考虑过现有功能是否能满足需求
          required: true