name: 🔒 Security Report
description: Report a security vulnerability (Please use private reporting for sensitive issues)
title: "[Security]: "
labels: ["security", "critical"]
assignees:
  - "@me"
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ 重要提醒
        
        如果您发现了严重的安全漏洞，请不要在公开的 Issue 中报告。
        请通过以下方式私密报告：
        - 使用 GitHub 的私密安全报告功能
        - 发送邮件到项目维护者
        
        对于一般性的安全改进建议，可以继续填写此表单。

  - type: dropdown
    id: severity
    attributes:
      label: 严重程度
      description: 这个安全问题的严重程度
      options:
        - 严重 (Critical) - 可能导致远程代码执行或数据泄露
        - 高 (High) - 可能导致权限提升或敏感信息暴露
        - 中 (Medium) - 可能导致拒绝服务或部分功能绕过
        - 低 (Low) - 一般性安全改进建议
        - 信息 (Info) - 安全最佳实践建议
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: 安全类别
      description: 这个安全问题属于哪个类别？
      options:
        - 代码注入 (Code Injection)
        - 路径遍历 (Path Traversal)
        - 认证绕过 (Authentication Bypass)
        - 权限提升 (Privilege Escalation)
        - 信息泄露 (Information Disclosure)
        - 拒绝服务 (Denial of Service)
        - 依赖漏洞 (Dependency Vulnerability)
        - 配置安全 (Configuration Security)
        - 其他
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: 漏洞描述
      description: 详细描述安全问题
      placeholder: |
        请详细描述发现的安全问题...
        
        注意：请避免在公开场合披露敏感的漏洞细节
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: 影响评估
      description: 这个漏洞可能造成什么影响？
      placeholder: |
        例如:
        - 攻击者可能获得什么访问权限
        - 可能泄露什么信息
        - 对系统稳定性的影响
        - 受影响的用户范围
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: 受影响版本
      description: 哪些版本受到此安全问题影响？
      placeholder: |
        例如:
        - 所有版本
        - v1.0.0 - v1.2.3
        - 最新开发版本
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 重现步骤
      description: 如何重现这个安全问题？（如果可以安全地公开）
      placeholder: |
        请提供重现步骤，但请注意不要包含可能被恶意利用的详细信息
        
        1. 第一步...
        2. 第二步...
        3. 观察到的安全问题...

  - type: textarea
    id: mitigation
    attributes:
      label: 缓解措施
      description: 您建议的临时缓解措施或修复建议
      placeholder: |
        例如:
        - 输入验证改进
        - 权限检查加强
        - 配置参数调整
        - 依赖版本升级

  - type: textarea
    id: references
    attributes:
      label: 参考资料
      description: 相关的CVE、安全公告或参考文档
      placeholder: |
        例如:
        - CVE-2023-xxxxx
        - 相关安全公告链接
        - 技术文档或最佳实践

  - type: checkboxes
    id: disclosure
    attributes:
      label: 披露协议
      description: 请确认您理解并同意以下条款
      options:
        - label: 我理解这是一个公开的报告，任何人都可以查看
          required: true
        - label: 我确认这不是一个需要私密处理的严重安全漏洞
          required: true
        - label: 我同意遵循负责任的漏洞披露原则
          required: true
        - label: 我不会在修复完成前公开披露详细的漏洞利用方法
          required: true